backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home'
        name: 'index'
        fields:
          - { label: 'Header Logo', name: 'headerLogo', widget: 'image' }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
  - name: 'projects'
    label: 'projects'
    folder: 'src/pages/projects'
    create: true
    fields:
      - { title: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project-page',
        }
      - {
          label: 'SEO Keywords (comma separated)',
          name: 'seoKeywords',
          widget: 'string',
        }
      - { label: 'Home Page Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Social Sharing Image', name: 'socialImage', widget: 'image' }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - { label: 'Image Title', name: 'imageTitle', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: Image Alt Text, name: 'altText', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
