backend:
  name: git-gateway
  branch: master
  
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home'
        name: 'index'
        fields:
          - { label: 'Header Logo', name: 'headerLogo', widget: 'image' }
          - label: 'Social Links'
            name: 'socialLinks'
            widget: 'list'
            fields:
              - {
                  label: 'Alt description',
                  hint: 'Text to use in place of image e.g. Instagram',
                  name: 'description',
                  widget: 'string',
                }
              - { label: 'URL', name: 'url', widget: 'string' }
              - {
                  label: 'Font Awesome Icon Classname',
                  hint: 'Text from the class property of the chosen icon from https://fontawesome.com/icons',
                  name: 'faIcon',
                  widget: string,
                }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
      - file: 'src/pages/about.md'
        label: 'About'
        name: 'about'
        fields:
          - {
            label: 'Content',
            name: 'content',
            widget: 'markdown'
          }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
      - file: 'src/pages/contact.md'
        label: 'Contact'
        name: 'contact'
        fields: 
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'contact-page',
            }
          - label: 'Links'
            name: 'contactLinks'
            widget: 'list'
            fields:
              - {
                  label: "Text",
                  hint: "Text to visibly show next to icon",
                  name: 'visibleText',
                  widget: 'string'
                }
              - {
                  label: 'Alt description',
                  hint: 'Text to use in place of image e.g. Instagram',
                  name: 'description',
                  widget: 'string',
                }
              - { label: 'URL', name: 'url', widget: 'string' }
              - {
                  label: 'Font Awesome Icon Classname',
                  hint: 'Text from the class property of the chosen icon from https://fontawesome.com/icons',
                  name: 'faIcon',
                  widget: string,
                }

  - name: 'projects'
    label: 'projects'
    folder: 'src/pages/projects'
    create: true
    fields:
      - { title: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project-page',
        }
      - {
          label: 'SEO Keywords (comma separated)',
          name: 'seoKeywords',
          widget: 'string',
        }
      - { label: 'Home Page Thumbnail', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Home Page Thumbnail Title',
          name: 'thumbnailTitle',
          widget: 'string',
        }
      - { label: 'Social Sharing Image', name: 'socialImage', widget: 'image' }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - { label: 'Image Title', name: 'imageTitle', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: Image Alt Text, name: 'altText', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
